/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MoodType = IDL.Variant({
  'sad' : IDL.Null,
  'tired' : IDL.Null,
  'anxious' : IDL.Null,
  'happy' : IDL.Null,
  'romantic' : IDL.Null,
  'loved' : IDL.Null,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({ 'user1' : IDL.Null, 'user2' : IDL.Null });
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const Answer = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'isCorrect' : IDL.Bool,
  'questionId' : IDL.Text,
  'answerText' : IDL.Text,
  'answererId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const Card = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'senderId' : IDL.Principal,
});
export const SurpriseDrop = IDL.Record({
  'id' : IDL.Text,
  'createdAt' : IDL.Int,
  'creatorId' : IDL.Principal,
  'unlockAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'recipientId' : IDL.Principal,
  'isRevealed' : IDL.Bool,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Memory = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'imageUrl' : IDL.Opt(IDL.Text),
  'addedBy' : IDL.Principal,
});
export const MoodTag = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'angry' : IDL.Null,
  'missYou' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'moodTag' : IDL.Opt(MoodTag),
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'seenBy' : IDL.Vec(IDL.Principal),
  'senderId' : IDL.Principal,
});
export const MoodEntry = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'mood' : MoodType,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
});
export const PeriodLog = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Principal,
  'date' : IDL.Text,
  'mood' : MoodType,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'isPeriodDay' : IDL.Bool,
  'partnerCanSeeDetails' : IDL.Bool,
  'symptoms' : IDL.Vec(IDL.Text),
});
export const Question = IDL.Record({
  'id' : IDL.Text,
  'authorId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
});
export const RelationshipStats = IDL.Record({ 'startDate' : IDL.Text });
export const User = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addPeriodLog' : IDL.Func(
      [
        IDL.Text,
        IDL.Bool,
        IDL.Vec(IDL.Text),
        MoodType,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addQuestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createDrop' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Int],
      [],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, UserRole], [], []),
  'deleteMemory' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAnswers' : IDL.Func([], [IDL.Vec(Answer)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getCardsFiltered' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Vec(Card)],
      ['query'],
    ),
  'getDropsForUser' : IDL.Func([], [IDL.Vec(SurpriseDrop)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getMemoriesSortedByDate' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getMemoriesSortedByTitle' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
  'getPeriodLogs' : IDL.Func([IDL.Principal], [IDL.Vec(PeriodLog)], ['query']),
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getRelationshipStats' : IDL.Func(
      [],
      [IDL.Opt(RelationshipStats)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logMood' : IDL.Func([MoodType, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'markCardAsRead' : IDL.Func([IDL.Text], [], []),
  'markMessageAsSeen' : IDL.Func([IDL.Text], [], []),
  'revealDrop' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(MoodTag)], [], []),
  'sendSorryCard' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'setRelationshipStartDate' : IDL.Func([IDL.Text], [], []),
  'submitAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'updatePeriodLog' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), MoodType, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MoodType = IDL.Variant({
    'sad' : IDL.Null,
    'tired' : IDL.Null,
    'anxious' : IDL.Null,
    'happy' : IDL.Null,
    'romantic' : IDL.Null,
    'loved' : IDL.Null,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({ 'user1' : IDL.Null, 'user2' : IDL.Null });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const Answer = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'isCorrect' : IDL.Bool,
    'questionId' : IDL.Text,
    'answerText' : IDL.Text,
    'answererId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const Card = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'senderId' : IDL.Principal,
  });
  const SurpriseDrop = IDL.Record({
    'id' : IDL.Text,
    'createdAt' : IDL.Int,
    'creatorId' : IDL.Principal,
    'unlockAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'recipientId' : IDL.Principal,
    'isRevealed' : IDL.Bool,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Memory = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'imageUrl' : IDL.Opt(IDL.Text),
    'addedBy' : IDL.Principal,
  });
  const MoodTag = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'angry' : IDL.Null,
    'missYou' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'moodTag' : IDL.Opt(MoodTag),
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'seenBy' : IDL.Vec(IDL.Principal),
    'senderId' : IDL.Principal,
  });
  const MoodEntry = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'mood' : MoodType,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
  });
  const PeriodLog = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Principal,
    'date' : IDL.Text,
    'mood' : MoodType,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'isPeriodDay' : IDL.Bool,
    'partnerCanSeeDetails' : IDL.Bool,
    'symptoms' : IDL.Vec(IDL.Text),
  });
  const Question = IDL.Record({
    'id' : IDL.Text,
    'authorId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
  });
  const RelationshipStats = IDL.Record({ 'startDate' : IDL.Text });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMemory' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addPeriodLog' : IDL.Func(
        [
          IDL.Text,
          IDL.Bool,
          IDL.Vec(IDL.Text),
          MoodType,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addQuestion' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createDrop' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text), IDL.Int],
        [],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, UserRole], [], []),
    'deleteMemory' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAnswers' : IDL.Func([], [IDL.Vec(Answer)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getCardsFiltered' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Vec(Card)],
        ['query'],
      ),
    'getDropsForUser' : IDL.Func([], [IDL.Vec(SurpriseDrop)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMemories' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getMemoriesSortedByDate' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getMemoriesSortedByTitle' : IDL.Func([], [IDL.Vec(Memory)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMoodEntries' : IDL.Func([], [IDL.Vec(MoodEntry)], ['query']),
    'getPeriodLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PeriodLog)],
        ['query'],
      ),
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getRelationshipStats' : IDL.Func(
        [],
        [IDL.Opt(RelationshipStats)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logMood' : IDL.Func([MoodType, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'markCardAsRead' : IDL.Func([IDL.Text], [], []),
    'markMessageAsSeen' : IDL.Func([IDL.Text], [], []),
    'revealDrop' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Opt(MoodTag)], [], []),
    'sendSorryCard' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'setRelationshipStartDate' : IDL.Func([IDL.Text], [], []),
    'submitAnswer' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'updatePeriodLog' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), MoodType, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };