/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer {
  'id' : string,
  'createdAt' : bigint,
  'isCorrect' : boolean,
  'questionId' : string,
  'answerText' : string,
  'answererId' : Principal,
}
export interface Card {
  'id' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'imageUrl' : [] | [string],
  'message' : string,
  'senderId' : Principal,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Memory {
  'id' : string,
  'title' : string,
  'note' : string,
  'createdAt' : bigint,
  'imageUrl' : [] | [string],
  'addedBy' : Principal,
}
export interface Message {
  'id' : string,
  'moodTag' : [] | [MoodTag],
  'createdAt' : bigint,
  'text' : string,
  'seenBy' : Array<Principal>,
  'senderId' : Principal,
}
export interface MoodEntry {
  'id' : string,
  'userId' : Principal,
  'date' : string,
  'mood' : MoodType,
  'note' : [] | [string],
  'createdAt' : bigint,
}
export type MoodTag = { 'sad' : null } |
  { 'happy' : null } |
  { 'angry' : null } |
  { 'missYou' : null };
export type MoodType = { 'sad' : null } |
  { 'tired' : null } |
  { 'anxious' : null } |
  { 'happy' : null } |
  { 'romantic' : null } |
  { 'loved' : null };
export interface PeriodLog {
  'id' : string,
  'ownerId' : Principal,
  'date' : string,
  'mood' : MoodType,
  'note' : [] | [string],
  'createdAt' : bigint,
  'isPeriodDay' : boolean,
  'partnerCanSeeDetails' : boolean,
  'symptoms' : Array<string>,
}
export interface Question {
  'id' : string,
  'authorId' : Principal,
  'createdAt' : bigint,
  'correctAnswer' : string,
  'questionText' : string,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface RelationshipStats { 'startDate' : string }
export interface SurpriseDrop {
  'id' : string,
  'createdAt' : bigint,
  'creatorId' : Principal,
  'unlockAt' : bigint,
  'imageUrl' : [] | [string],
  'message' : string,
  'recipientId' : Principal,
  'isRevealed' : boolean,
}
export type Time = bigint;
export interface User { 'id' : Principal, 'name' : string, 'role' : UserRole }
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'user1' : null } |
  { 'user2' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMemory' : ActorMethod<[string, string, [] | [string]], undefined>,
  'addPeriodLog' : ActorMethod<
    [string, boolean, Array<string>, MoodType, [] | [string], boolean],
    undefined
  >,
  'addQuestion' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createDrop' : ActorMethod<
    [Principal, string, [] | [string], bigint],
    undefined
  >,
  'createUser' : ActorMethod<[string, UserRole], undefined>,
  'deleteMemory' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAnswers' : ActorMethod<[], Array<Answer>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCards' : ActorMethod<[], Array<Card>>,
  'getCardsFiltered' : ActorMethod<[string, boolean], Array<Card>>,
  'getDropsForUser' : ActorMethod<[], Array<SurpriseDrop>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMemories' : ActorMethod<[], Array<Memory>>,
  'getMemoriesSortedByDate' : ActorMethod<[], Array<Memory>>,
  'getMemoriesSortedByTitle' : ActorMethod<[], Array<Memory>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getMoodEntries' : ActorMethod<[], Array<MoodEntry>>,
  'getPeriodLogs' : ActorMethod<[Principal], Array<PeriodLog>>,
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'getRelationshipStats' : ActorMethod<[], [] | [RelationshipStats]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logMood' : ActorMethod<[MoodType, string, [] | [string]], undefined>,
  'markCardAsRead' : ActorMethod<[string], undefined>,
  'markMessageAsSeen' : ActorMethod<[string], undefined>,
  'revealDrop' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, [] | [MoodTag]], undefined>,
  'sendSorryCard' : ActorMethod<[string, [] | [string]], undefined>,
  'setRelationshipStartDate' : ActorMethod<[string], undefined>,
  'submitAnswer' : ActorMethod<[string, string], boolean>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updatePeriodLog' : ActorMethod<
    [string, Array<string>, MoodType, [] | [string], boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];