/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Card {
    id: string;
    createdAt: bigint;
    isRead: boolean;
    imageUrl?: string;
    message: string;
    senderId: Principal;
}
export interface User {
    id: Principal;
    name: string;
    role: UserRole;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SurpriseDrop {
    id: string;
    createdAt: bigint;
    creatorId: Principal;
    unlockAt: bigint;
    imageUrl?: string;
    message: string;
    recipientId: Principal;
    isRevealed: boolean;
}
export interface RelationshipStats {
    startDate: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface MoodEntry {
    id: string;
    userId: Principal;
    date: string;
    mood: MoodType;
    note?: string;
    createdAt: bigint;
}
export interface PeriodLog {
    id: string;
    ownerId: Principal;
    date: string;
    mood: MoodType;
    note?: string;
    createdAt: bigint;
    isPeriodDay: boolean;
    partnerCanSeeDetails: boolean;
    symptoms: Array<string>;
}
export interface Memory {
    id: string;
    title: string;
    note: string;
    createdAt: bigint;
    imageUrl?: string;
    addedBy: Principal;
}
export interface Message {
    id: string;
    moodTag?: MoodTag;
    createdAt: bigint;
    text: string;
    seenBy: Array<Principal>;
    senderId: Principal;
}
export interface Answer {
    id: string;
    createdAt: bigint;
    isCorrect: boolean;
    questionId: string;
    answerText: string;
    answererId: Principal;
}
export interface Question {
    id: string;
    authorId: Principal;
    createdAt: bigint;
    correctAnswer: string;
    questionText: string;
}
export interface UserProfile {
    name: string;
    role: UserRole;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MoodTag {
    sad = "sad",
    happy = "happy",
    angry = "angry",
    missYou = "missYou"
}
export enum MoodType {
    sad = "sad",
    tired = "tired",
    anxious = "anxious",
    happy = "happy",
    romantic = "romantic",
    loved = "loved"
}
export enum UserRole {
    user1 = "user1",
    user2 = "user2"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMemory(title: string, note: string, imageUrl: string | null): Promise<void>;
    addPeriodLog(date: string, isPeriodDay: boolean, symptoms: Array<string>, mood: MoodType, note: string | null, partnerCanSeeDetails: boolean): Promise<void>;
    addQuestion(questionText: string, correctAnswer: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createDrop(recipientId: Principal, message: string, imageUrl: string | null, unlockAt: bigint): Promise<void>;
    createUser(name: string, role: UserRole): Promise<void>;
    deleteMemory(memoryId: string): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAnswers(): Promise<Array<Answer>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCards(): Promise<Array<Card>>;
    getCardsFiltered(messageFilter: string, senderOnly: boolean): Promise<Array<Card>>;
    getDropsForUser(): Promise<Array<SurpriseDrop>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getMemories(): Promise<Array<Memory>>;
    getMemoriesSortedByDate(): Promise<Array<Memory>>;
    getMemoriesSortedByTitle(): Promise<Array<Memory>>;
    getMessages(): Promise<Array<Message>>;
    getMoodEntries(): Promise<Array<MoodEntry>>;
    getPeriodLogs(owner: Principal): Promise<Array<PeriodLog>>;
    getQuestions(): Promise<Array<Question>>;
    getRelationshipStats(): Promise<RelationshipStats | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<User>>;
    isCallerAdmin(): Promise<boolean>;
    logMood(mood: MoodType, date: string, note: string | null): Promise<void>;
    markCardAsRead(cardId: string): Promise<void>;
    markMessageAsSeen(messageId: string): Promise<void>;
    revealDrop(dropId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(text: string, moodTag: MoodTag | null): Promise<void>;
    sendSorryCard(message: string, imageUrl: string | null): Promise<void>;
    setRelationshipStartDate(date: string): Promise<void>;
    submitAnswer(questionId: string, answerText: string): Promise<boolean>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    updatePeriodLog(logId: string, symptoms: Array<string>, mood: MoodType, note: string | null, partnerCanSeeDetails: boolean): Promise<void>;
}
import type { Card as _Card, Memory as _Memory, Message as _Message, MoodEntry as _MoodEntry, MoodTag as _MoodTag, MoodType as _MoodType, PeriodLog as _PeriodLog, RelationshipStats as _RelationshipStats, SurpriseDrop as _SurpriseDrop, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMemory(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMemory(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMemory(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addPeriodLog(arg0: string, arg1: boolean, arg2: Array<string>, arg3: MoodType, arg4: string | null, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPeriodLog(arg0, arg1, arg2, to_candid_MoodType_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPeriodLog(arg0, arg1, arg2, to_candid_MoodType_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async addQuestion(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createDrop(arg0: Principal, arg1: string, arg2: string | null, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDrop(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDrop(arg0, arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createUser(arg0: string, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteMemory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMemory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMemory(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAnswers(): Promise<Array<Answer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnswers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnswers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCards(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCards();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCards();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardsFiltered(arg0: string, arg1: boolean): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardsFiltered(arg0, arg1);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardsFiltered(arg0, arg1);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDropsForUser(): Promise<Array<SurpriseDrop>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDropsForUser();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDropsForUser();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getMemories(): Promise<Array<Memory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemories();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemories();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemoriesSortedByDate(): Promise<Array<Memory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoriesSortedByDate();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoriesSortedByDate();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMemoriesSortedByTitle(): Promise<Array<Memory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMemoriesSortedByTitle();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMemoriesSortedByTitle();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMoodEntries(): Promise<Array<MoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodEntries();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodEntries();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPeriodLogs(arg0: Principal): Promise<Array<PeriodLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPeriodLogs(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPeriodLogs(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestions();
            return result;
        }
    }
    async getRelationshipStats(): Promise<RelationshipStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRelationshipStats();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRelationshipStats();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logMood(arg0: MoodType, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logMood(to_candid_MoodType_n9(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logMood(to_candid_MoodType_n9(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async markCardAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markCardAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCardAsRead(arg0);
            return result;
        }
    }
    async markMessageAsSeen(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsSeen(arg0);
            return result;
        }
    }
    async revealDrop(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revealDrop(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revealDrop(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n50(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: MoodTag | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, to_candid_opt_n52(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async sendSorryCard(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSorryCard(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSorryCard(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setRelationshipStartDate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRelationshipStartDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRelationshipStartDate(arg0);
            return result;
        }
    }
    async submitAnswer(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePeriodLog(arg0: string, arg1: Array<string>, arg2: MoodType, arg3: string | null, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePeriodLog(arg0, arg1, to_candid_MoodType_n9(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePeriodLog(arg0, arg1, to_candid_MoodType_n9(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_Card_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Card {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Memory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Memory): Memory {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_MoodEntry_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodEntry): MoodEntry {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_MoodTag_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodTag): MoodTag {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_MoodType_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MoodType): MoodType {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PeriodLog_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PeriodLog): PeriodLog {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_SurpriseDrop_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SurpriseDrop): SurpriseDrop {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_User_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MoodTag]): MoodTag | null {
    return value.length === 0 ? null : from_candid_MoodTag_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RelationshipStats]): RelationshipStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: bigint;
    isRead: boolean;
    imageUrl: [] | [string];
    message: string;
    senderId: Principal;
}): {
    id: string;
    createdAt: bigint;
    isRead: boolean;
    imageUrl?: string;
    message: string;
    senderId: Principal;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        isRead: value.isRead,
        imageUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.imageUrl)),
        message: value.message,
        senderId: value.senderId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    createdAt: bigint;
    creatorId: Principal;
    unlockAt: bigint;
    imageUrl: [] | [string];
    message: string;
    recipientId: Principal;
    isRevealed: boolean;
}): {
    id: string;
    createdAt: bigint;
    creatorId: Principal;
    unlockAt: bigint;
    imageUrl?: string;
    message: string;
    recipientId: Principal;
    isRevealed: boolean;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        creatorId: value.creatorId,
        unlockAt: value.unlockAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.imageUrl)),
        message: value.message,
        recipientId: value.recipientId,
        isRevealed: value.isRevealed
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    note: string;
    createdAt: bigint;
    imageUrl: [] | [string];
    addedBy: Principal;
}): {
    id: string;
    title: string;
    note: string;
    createdAt: bigint;
    imageUrl?: string;
    addedBy: Principal;
} {
    return {
        id: value.id,
        title: value.title,
        note: value.note,
        createdAt: value.createdAt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.imageUrl)),
        addedBy: value.addedBy
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    moodTag: [] | [_MoodTag];
    createdAt: bigint;
    text: string;
    seenBy: Array<Principal>;
    senderId: Principal;
}): {
    id: string;
    moodTag?: MoodTag;
    createdAt: bigint;
    text: string;
    seenBy: Array<Principal>;
    senderId: Principal;
} {
    return {
        id: value.id,
        moodTag: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.moodTag)),
        createdAt: value.createdAt,
        text: value.text,
        seenBy: value.seenBy,
        senderId: value.senderId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userId: Principal;
    date: string;
    mood: _MoodType;
    note: [] | [string];
    createdAt: bigint;
}): {
    id: string;
    userId: Principal;
    date: string;
    mood: MoodType;
    note?: string;
    createdAt: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        date: value.date,
        mood: from_candid_MoodType_n41(_uploadFile, _downloadFile, value.mood),
        note: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    ownerId: Principal;
    date: string;
    mood: _MoodType;
    note: [] | [string];
    createdAt: bigint;
    isPeriodDay: boolean;
    partnerCanSeeDetails: boolean;
    symptoms: Array<string>;
}): {
    id: string;
    ownerId: Principal;
    date: string;
    mood: MoodType;
    note?: string;
    createdAt: bigint;
    isPeriodDay: boolean;
    partnerCanSeeDetails: boolean;
    symptoms: Array<string>;
} {
    return {
        id: value.id,
        ownerId: value.ownerId,
        date: value.date,
        mood: from_candid_MoodType_n41(_uploadFile, _downloadFile, value.mood),
        note: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        isPeriodDay: value.isPeriodDay,
        partnerCanSeeDetails: value.partnerCanSeeDetails,
        symptoms: value.symptoms
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    role: _UserRole;
}): {
    id: Principal;
    name: string;
    role: UserRole;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user1: null;
} | {
    user2: null;
}): UserRole {
    return "user1" in value ? UserRole.user1 : "user2" in value ? UserRole.user2 : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    missYou: null;
}): MoodTag {
    return "sad" in value ? MoodTag.sad : "happy" in value ? MoodTag.happy : "angry" in value ? MoodTag.angry : "missYou" in value ? MoodTag.missYou : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    tired: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    romantic: null;
} | {
    loved: null;
}): MoodType {
    return "sad" in value ? MoodType.sad : "tired" in value ? MoodType.tired : "anxious" in value ? MoodType.anxious : "happy" in value ? MoodType.happy : "romantic" in value ? MoodType.romantic : "loved" in value ? MoodType.loved : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Array<Card> {
    return value.map((x)=>from_candid_Card_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SurpriseDrop>): Array<SurpriseDrop> {
    return value.map((x)=>from_candid_SurpriseDrop_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Memory>): Array<Memory> {
    return value.map((x)=>from_candid_Memory_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MoodEntry>): Array<MoodEntry> {
    return value.map((x)=>from_candid_MoodEntry_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PeriodLog>): Array<PeriodLog> {
    return value.map((x)=>from_candid_PeriodLog_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n48(_uploadFile, _downloadFile, x));
}
function to_candid_MoodTag_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodTag): _MoodTag {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_MoodType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodType): _MoodType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodTag | null): [] | [_MoodTag] {
    return value === null ? candid_none() : candid_some(to_candid_MoodTag_n53(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n13(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodType): {
    sad: null;
} | {
    tired: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    romantic: null;
} | {
    loved: null;
} {
    return value == MoodType.sad ? {
        sad: null
    } : value == MoodType.tired ? {
        tired: null
    } : value == MoodType.anxious ? {
        anxious: null
    } : value == MoodType.happy ? {
        happy: null
    } : value == MoodType.romantic ? {
        romantic: null
    } : value == MoodType.loved ? {
        loved: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    user1: null;
} | {
    user2: null;
} {
    return value == UserRole.user1 ? {
        user1: null
    } : value == UserRole.user2 ? {
        user2: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MoodTag): {
    sad: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    missYou: null;
} {
    return value == MoodTag.sad ? {
        sad: null
    } : value == MoodTag.happy ? {
        happy: null
    } : value == MoodTag.angry ? {
        angry: null
    } : value == MoodTag.missYou ? {
        missYou: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
